# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
