# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
